// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qloqoqzsnvljgtkxxlom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsb3FvcXpzbnZsamd0a3h4bG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjQwNjYsImV4cCI6MjA2MDYwMDA2Nn0.7Blqx4mdWRz-4BuaMXyi4qiAYgvCuvJ-XLG7afEz-04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);